namespace ZoomMeetings.Cli;

public record ToolInfo(
    string Domain,
    string OperationId,
    string MethodName,
    string HttpMethod,
    string Path,
    string Description
);

public static class ToolCatalog
{
    public static readonly IReadOnlyList<ToolInfo> Tools = new List<ToolInfo>
    {
        // 1. Meetings (27 tools)
        new("Meetings", "meetingDelete", "DeleteMeetingAsync", "DELETE", "/meetings/{meetingId}", "Permanently delete a scheduled or past meeting"),
        new("Meetings", "meeting", "GetMeetingAsync", "GET", "/meetings/{meetingId}", "Retrieve details and settings of a scheduled or past meeting"),
        new("Meetings", "meetingUpdate", "UpdateMeetingAsync", "PATCH", "/meetings/{meetingId}", "Update meeting settings, topic, start time, or recurrence"),
        new("Meetings", "meetingInvitation", "GetMeetingInvitationAsync", "GET", "/meetings/{meetingId}/invitation", "Retrieve the generated meeting invitation text and dial-in numbers"),
        new("Meetings", "meetingInviteLinksCreate", "CreateMeetingInviteLinksAsync", "POST", "/meetings/{meetingId}/invite_links", "Generate customized invite links for meeting attendees"),
        new("Meetings", "meetingLiveStreamingJoinToken", "GetMeetingLiveStreamingJoinTokenAsync", "GET", "/meetings/{meetingId}/jointoken/live_streaming", "Get join token for live streaming meeting"),
        new("Meetings", "meetingLocalArchivingArchiveToken", "GetMeetingLocalArchivingTokenAsync", "GET", "/meetings/{meetingId}/jointoken/local_archiving", "Get token for local archiving of meeting"),
        new("Meetings", "meetingLocalRecordingJoinToken", "GetMeetingLocalRecordingJoinTokenAsync", "GET", "/meetings/{meetingId}/jointoken/local_recording", "Get token for local recording of meeting"),
        new("Meetings", "getMeetingLiveStreamDetails", "GetMeetingLiveStreamAsync", "GET", "/meetings/{meetingId}/livestream", "Get configured live stream settings, broadcast URL, and stream key"),
        new("Meetings", "meetingLiveStreamUpdate", "UpdateMeetingLiveStreamAsync", "PATCH", "/meetings/{meetingId}/livestream", "Configure live streaming broadcast URL, page URL, and stream key"),
        new("Meetings", "meetingLiveStreamStatusUpdate", "UpdateMeetingLiveStreamStatusAsync", "PATCH", "/meetings/{meetingId}/livestream/status", "Start or stop live streaming broadcast for a meeting"),
        new("Meetings", "meetingAppDelete", "DeleteMeetingOpenAppsAsync", "DELETE", "/meetings/{meetingId}/open_apps", "Delete opened Zoom Apps from a meeting session"),
        new("Meetings", "meetingAppAdd", "AddMeetingOpenAppsAsync", "POST", "/meetings/{meetingId}/open_apps", "Open a Zoom App in a meeting session"),
        new("Meetings", "getSipDialingWithPasscode", "GetMeetingSipDialingAsync", "POST", "/meetings/{meetingId}/sip_dialing", "Request Cloud Room Connector (CRC) SIP dialing with encrypted passcode"),
        new("Meetings", "meetingStatus", "UpdateMeetingStatusAsync", "PUT", "/meetings/{meetingId}/status", "End an active meeting session"),
        new("Meetings", "meetingSurveyDelete", "DeleteMeetingSurveyAsync", "DELETE", "/meetings/{meetingId}/survey", "Delete post-meeting attendee survey"),
        new("Meetings", "meetingSurveyGet", "GetMeetingSurveyAsync", "GET", "/meetings/{meetingId}/survey", "Retrieve post-meeting survey questions, settings, and 3rd party URL"),
        new("Meetings", "meetingSurveyUpdate", "UpdateMeetingSurveyAsync", "PATCH", "/meetings/{meetingId}/survey", "Create or update post-meeting survey questions and feedback options"),
        new("Meetings", "meetingToken", "GetMeetingTokenAsync", "GET", "/meetings/{meetingId}/token", "Generate user join or host token for meeting"),
        new("Meetings", "pastMeetingDetails", "GetPastMeetingDetailsAsync", "GET", "/past_meetings/{meetingId}", "Retrieve duration, start/end timestamps of an ended meeting"),
        new("Meetings", "pastMeetings", "GetPastMeetingInstancesAsync", "GET", "/past_meetings/{meetingId}/instances", "List past instances and UUIDs of a recurring meeting"),
        new("Meetings", "pastMeetingParticipants", "GetPastMeetingParticipantsAsync", "GET", "/past_meetings/{meetingId}/participants", "List participants who attended a past meeting"),
        new("Meetings", "listPastMeetingQA", "GetPastMeetingQaAsync", "GET", "/past_meetings/{meetingId}/qa", "Retrieve Q&A questions and answers asked during a past meeting"),
        new("Meetings", "meetings", "ListMeetingsAsync", "GET", "/users/{userId}/meetings", "List scheduled, recurring, and upcoming meetings for a user"),
        new("Meetings", "meetingCreate", "CreateMeetingAsync", "POST", "/users/{userId}/meetings", "Schedule an instant or future meeting for a user"),
        new("Meetings", "userPACs", "GetUserPacsAsync", "GET", "/users/{userId}/pac", "List Personal Audio Conference (PAC) accounts for a user"),
        new("Meetings", "listUpcomingMeeting", "ListUpcomingMeetingsAsync", "GET", "/users/{userId}/upcoming_meetings", "List upcoming scheduled meetings for a user"),

        // 2. Registrants (8 tools)
        new("Registrants", "addBatchRegistrants", "CreateBatchRegistrantsAsync", "POST", "/meetings/{meetingId}/batch_registrants", "Register multiple attendees in bulk for a meeting (auto-approve)"),
        new("Registrants", "meetingRegistrants", "ListRegistrantsAsync", "GET", "/meetings/{meetingId}/registrants", "List approved, pending, or denied registrants for a meeting"),
        new("Registrants", "meetingRegistrantCreate", "AddRegistrantAsync", "POST", "/meetings/{meetingId}/registrants", "Register a single attendee with custom field responses"),
        new("Registrants", "meetingRegistrantsQuestionsGet", "GetRegistrationQuestionsAsync", "GET", "/meetings/{meetingId}/registrants/questions", "Retrieve required registration questions and custom fields"),
        new("Registrants", "meetingRegistrantQuestionUpdate", "UpdateRegistrationQuestionsAsync", "PATCH", "/meetings/{meetingId}/registrants/questions", "Configure custom registration questions and required fields"),
        new("Registrants", "meetingRegistrantStatus", "UpdateRegistrantStatusAsync", "PUT", "/meetings/{meetingId}/registrants/status", "Approve, deny, or cancel registrant admission status"),
        new("Registrants", "meetingregistrantdelete", "DeleteRegistrantAsync", "DELETE", "/meetings/{meetingId}/registrants/{registrantId}", "Delete a registered attendee from a meeting"),
        new("Registrants", "meetingRegistrantGet", "GetRegistrantAsync", "GET", "/meetings/{meetingId}/registrants/{registrantId}", "Get details and join link for a specific meeting registrant"),

        // 3. Polls (7 tools)
        new("Polls", "createBatchPolls", "CreateBatchPollsAsync", "POST", "/meetings/{meetingId}/batch_polls", "Create multiple polls or quizzes in bulk for a meeting"),
        new("Polls", "meetingPolls", "ListPollsAsync", "GET", "/meetings/{meetingId}/polls", "List all polls and quizzes configured for a meeting"),
        new("Polls", "meetingPollCreate", "CreatePollAsync", "POST", "/meetings/{meetingId}/polls", "Create a poll or quiz with single/multiple choice questions"),
        new("Polls", "meetingPollDelete", "DeletePollAsync", "DELETE", "/meetings/{meetingId}/polls/{pollId}", "Delete a poll or quiz from a meeting"),
        new("Polls", "meetingPollGet", "GetPollAsync", "GET", "/meetings/{meetingId}/polls/{pollId}", "Retrieve questions, answers, and correct choices for a poll"),
        new("Polls", "meetingPollUpdate", "UpdatePollAsync", "PUT", "/meetings/{meetingId}/polls/{pollId}", "Update questions, options, and quiz scoring for a poll"),
        new("Polls", "listPastMeetingPolls", "GetPastMeetingPollsAsync", "GET", "/past_meetings/{meetingId}/polls", "Retrieve voting and quiz results submitted in a past meeting"),

        // 4. Recordings/Archiving (23 tools)
        new("Recordings/Archiving", "listArchivedFiles", "ListArchivedFilesAsync", "GET", "/archive_files", "List archived compliance files across the account"),
        new("Recordings/Archiving", "listArchiveFileDownloadAudit", "ListArchiveFileDownloadAuditAsync", "GET", "/archive_files/download_audit", "Audit log of who downloaded archived compliance files"),
        new("Recordings/Archiving", "getArchivedFileStatistics", "GetArchivedFileStatisticsAsync", "GET", "/archive_files/statistics", "Get summary metrics and storage of archived compliance files"),
        new("Recordings/Archiving", "updateArchivedFile", "UpdateArchivedFileAsync", "PATCH", "/archive_files/{fileId}", "Update retention period or auto-delete status for an archived file"),
        new("Recordings/Archiving", "recordingDelete", "DeleteRecordingsAsync", "DELETE", "/meetings/{meetingId}/recordings", "Delete all cloud recordings for a meeting (trash or permanent)"),
        new("Recordings/Archiving", "recordingGet", "GetRecordingsAsync", "GET", "/meetings/{meetingId}/recordings", "Retrieve cloud recording video, audio, chat files, and download tokens"),
        new("Recordings/Archiving", "analytics_details", "GetRecordingAnalyticsDetailsAsync", "GET", "/meetings/{meetingId}/recordings/analytics_details", "Detailed viewer logs for on-demand cloud recordings"),
        new("Recordings/Archiving", "analytics_summary", "GetRecordingAnalyticsSummaryAsync", "GET", "/meetings/{meetingId}/recordings/analytics_summary", "Summary metrics of cloud recording views and downloads"),
        new("Recordings/Archiving", "meetingRecordingRegistrants", "ListRecordingRegistrantsAsync", "GET", "/meetings/{meetingId}/recordings/registrants", "List registrants registered to view on-demand cloud recordings"),
        new("Recordings/Archiving", "meetingRecordingRegistrantCreate", "CreateRecordingRegistrantAsync", "POST", "/meetings/{meetingId}/recordings/registrants", "Register a user for on-demand cloud recording access"),
        new("Recordings/Archiving", "recordingRegistrantsQuestionsGet", "GetRecordingRegistrationQuestionsAsync", "GET", "/meetings/{meetingId}/recordings/registrants/questions", "Get registration form questions for on-demand recording"),
        new("Recordings/Archiving", "recordingRegistrantQuestionUpdate", "UpdateRecordingRegistrationQuestionsAsync", "PATCH", "/meetings/{meetingId}/recordings/registrants/questions", "Update registration form questions for on-demand recording"),
        new("Recordings/Archiving", "meetingRecordingRegistrantStatus", "UpdateRecordingRegistrantStatusAsync", "PUT", "/meetings/{meetingId}/recordings/registrants/status", "Approve or deny viewer registration for on-demand recording"),
        new("Recordings/Archiving", "recordingSettingUpdate", "GetRecordingSettingsAsync", "GET", "/meetings/{meetingId}/recordings/settings", "Get cloud recording sharing password, expiry, and download settings"),
        new("Recordings/Archiving", "recordingSettingsUpdate", "UpdateRecordingSettingsAsync", "PATCH", "/meetings/{meetingId}/recordings/settings", "Update cloud recording access password, sharing, and download flags"),
        new("Recordings/Archiving", "recordingDeleteOne", "DeleteRecordingFileAsync", "DELETE", "/meetings/{meetingId}/recordings/{recordingId}", "Delete a single recording file (video, audio, or chat)"),
        new("Recordings/Archiving", "recordingStatusUpdateOne", "RecoverRecordingFileAsync", "PUT", "/meetings/{meetingId}/recordings/{recordingId}/status", "Recover a deleted recording file from trash"),
        new("Recordings/Archiving", "DeleteMeetingTranscript", "DeleteMeetingTranscriptAsync", "DELETE", "/meetings/{meetingId}/transcript", "Delete audio transcript file for a meeting"),
        new("Recordings/Archiving", "GetMeetingTranscript", "GetMeetingTranscriptAsync", "GET", "/meetings/{meetingId}/transcript", "Retrieve AI audio transcript (VTT format) for a meeting"),
        new("Recordings/Archiving", "recordingStatusUpdate", "RecoverMeetingRecordingsAsync", "PUT", "/meetings/{meetingUUID}/recordings/status", "Recover all deleted recording files for a meeting UUID from trash"),
        new("Recordings/Archiving", "deleteArchivedFiles", "DeletePastMeetingArchivedFilesAsync", "DELETE", "/past_meetings/{meetingUUID}/archive_files", "Delete archived compliance files for a past meeting UUID"),
        new("Recordings/Archiving", "getArchivedFiles", "GetPastMeetingArchivedFilesAsync", "GET", "/past_meetings/{meetingUUID}/archive_files", "Retrieve archived compliance files for a past meeting UUID"),
        new("Recordings/Archiving", "recordingsList", "ListUserRecordingsAsync", "GET", "/users/{userId}/recordings", "List all cloud recordings owned by a user in a date range"),

        // 5. Meeting Summaries (4 tools)
        new("Meeting Summaries", "Listmeetingsummaries", "ListMeetingSummariesAsync", "GET", "/meetings/meeting_summaries", "List AI Companion meeting summaries across the account"),
        new("Meeting Summaries", "Deletemeetingorwebinarsummary", "DeleteMeetingSummaryAsync", "DELETE", "/meetings/{meetingId}/meeting_summary", "Delete an AI Companion meeting or webinar summary"),
        new("Meeting Summaries", "Getameetingsummary", "GetMeetingSummaryAsync", "GET", "/meetings/{meetingId}/meeting_summary", "Retrieve AI Companion summary, chapters, and next action items"),
        new("Meeting Summaries", "ListUserMeetingSummaries", "ListUserMeetingSummariesAsync", "GET", "/users/{userId}/meeting_summaries", "List AI Companion summaries for meetings hosted by a user"),

        // 6. Reports (24 tools)
        new("Reports", "reportSignInSignOutActivities", "GetActivitiesReportAsync", "GET", "/report/activities", "Audit user sign-in and sign-out activities with IP and client type"),
        new("Reports", "getBillingReport", "GetBillingReportAsync", "GET", "/report/billing", "Get billing department usage and subscription report"),
        new("Reports", "getBillingInvoicesReports", "GetBillingInvoicesReportAsync", "GET", "/report/billing/invoices", "Get billing invoice history and payment statuses"),
        new("Reports", "reportCloudRecording", "GetCloudRecordingReportAsync", "GET", "/report/cloud_recording", "Get cloud recording storage usage per user and account total"),
        new("Reports", "reportDaily", "GetDailyReportAsync", "GET", "/report/daily", "Daily account metrics: new users, active meetings, participant minutes"),
        new("Reports", "Getdisclaimerreport", "GetDisclaimerReportAsync", "GET", "/report/disclaimer", "Audit log of users who acknowledged the custom account disclaimer"),
        new("Reports", "Gethistorymeetingandwebinarlist", "GetHistoryMeetingsReportAsync", "GET", "/report/history_meetings", "List historical meetings and webinars with UUIDs for compliance auditing"),
        new("Reports", "reportMeetingactivitylogs", "GetMeetingActivityLogsReportAsync", "GET", "/report/meeting_activities", "Host and participant in-meeting activity events (screen share, recording)"),
        new("Reports", "reportMeetingDetails", "GetMeetingReportDetailsAsync", "GET", "/report/meetings/{meetingId}", "Session metrics, host info, and participant count for an ended meeting"),
        new("Reports", "reportMeetingParticipants", "GetMeetingParticipantsReportAsync", "GET", "/report/meetings/{meetingId}/participants", "Detailed participant join/leave timestamps and duration in meeting"),
        new("Reports", "reportMeetingPolls", "GetMeetingPollsReportAsync", "GET", "/report/meetings/{meetingId}/polls", "Comprehensive poll responses and participant votes for a meeting"),
        new("Reports", "reportMeetingQA", "GetMeetingQaReportAsync", "GET", "/report/meetings/{meetingId}/qa", "Report of all questions asked and answered during a meeting"),
        new("Reports", "reportMeetingSurvey", "GetMeetingSurveyReportAsync", "GET", "/report/meetings/{meetingId}/survey", "Attendee survey responses and satisfaction scores for a meeting"),
        new("Reports", "reportOperationLogs", "GetOperationLogsReportAsync", "GET", "/report/operationlogs", "Administrator operation and audit change logs"),
        new("Reports", "Getremotesupportreport", "GetRemoteSupportReportAsync", "GET", "/report/remote_support", "Remote support sessions and duration audit report"),
        new("Reports", "reportTelephone", "GetTelephoneReportAsync", "GET", "/report/telephone", "Telephone dial-in/call-out minutes and toll usage report"),
        new("Reports", "reportUpcomingEvents", "GetUpcomingEventsReportAsync", "GET", "/report/upcoming_events", "Report of scheduled upcoming meetings and webinars across account"),
        new("Reports", "reportUsers", "GetUsersReportAsync", "GET", "/report/users", "Active, inactive, and pending user account status report"),
        new("Reports", "reportMeetings", "GetUserMeetingsReportAsync", "GET", "/report/users/{userId}/meetings", "Report of all past meetings hosted by a specific user"),
        new("Reports", "reportWebinarDetails", "GetWebinarReportDetailsAsync", "GET", "/report/webinars/{webinarId}", "Webinar session overview, peak attendee count, and duration"),
        new("Reports", "reportWebinarParticipants", "GetWebinarParticipantsReportAsync", "GET", "/report/webinars/{webinarId}/participants", "Webinar attendee attendance logs and engagement duration"),
        new("Reports", "reportWebinarPolls", "GetWebinarPollsReportAsync", "GET", "/report/webinars/{webinarId}/polls", "Poll responses and voting breakdown for a webinar"),
        new("Reports", "reportWebinarQA", "GetWebinarQaReportAsync", "GET", "/report/webinars/{webinarId}/qa", "Q&A log of questions, upvotes, and panelist answers in a webinar"),
        new("Reports", "reportWebinarSurvey", "GetWebinarSurveyReportAsync", "GET", "/report/webinars/{webinarId}/survey", "Attendee survey feedback and ratings for a webinar"),

        // 7. Webinars (53 tools)
        new("Webinars", "deleteWebinarChatMessageById", "DeleteWebinarChatMessageAsync", "DELETE", "/live_webinars/{webinarId}/chat/messages/{messageId}", "Delete a chat message from an active webinar session"),
        new("Webinars", "webinarAbsentees", "GetPastWebinarAbsenteesAsync", "GET", "/past_webinars/{webinarId}/absentees", "List registrants who registered but did not attend a past webinar"),
        new("Webinars", "pastWebinars", "GetPastWebinarInstancesAsync", "GET", "/past_webinars/{webinarId}/instances", "List past instances of a recurring webinar series"),
        new("Webinars", "listWebinarParticipants", "GetPastWebinarParticipantsAsync", "GET", "/past_webinars/{webinarId}/participants", "List attendees, panelists, and hosts from an ended webinar"),
        new("Webinars", "listPastWebinarPollResults", "GetPastWebinarPollsAsync", "GET", "/past_webinars/{webinarId}/polls", "Retrieve voting results and quiz scores from a past webinar"),
        new("Webinars", "listPastWebinarQA", "GetPastWebinarQaAsync", "GET", "/past_webinars/{webinarId}/qa", "Retrieve all Q&A interactions from a past webinar"),
        new("Webinars", "listWebinarTemplates", "ListWebinarTemplatesAsync", "GET", "/users/{userId}/webinar_templates", "List reusable webinar templates available for a user"),
        new("Webinars", "webinarTemplateCreate", "CreateWebinarTemplateAsync", "POST", "/users/{userId}/webinar_templates", "Create a reusable webinar template from an existing webinar"),
        new("Webinars", "webinars", "ListWebinarsAsync", "GET", "/users/{userId}/webinars", "List scheduled webinars for a user"),
        new("Webinars", "webinarCreate", "CreateWebinarAsync", "POST", "/users/{userId}/webinars", "Schedule a new webinar for a user"),
        new("Webinars", "webinarDelete", "DeleteWebinarAsync", "DELETE", "/webinars/{webinarId}", "Permanently delete a scheduled webinar"),
        new("Webinars", "webinar", "GetWebinarAsync", "GET", "/webinars/{webinarId}", "Retrieve configuration, settings, and join URL of a webinar"),
        new("Webinars", "webinarUpdate", "UpdateWebinarAsync", "PATCH", "/webinars/{webinarId}", "Update webinar topic, schedule, recurrence, and security settings"),
        new("Webinars", "addBatchWebinarRegistrants", "CreateBatchWebinarRegistrantsAsync", "POST", "/webinars/{webinarId}/batch_registrants", "Bulk register up to 30 attendees for a webinar"),
        new("Webinars", "getWebinarBranding", "GetWebinarBrandingAsync", "GET", "/webinars/{webinarId}/branding", "Get webinar branding assets (wallpaper, virtual backgrounds, name tags)"),
        new("Webinars", "deleteWebinarBrandingNameTag", "DeleteWebinarBrandingNameTagAsync", "DELETE", "/webinars/{webinarId}/branding/name_tags", "Delete all customized name tags from a webinar"),
        new("Webinars", "createWebinarBrandingNameTag", "CreateWebinarBrandingNameTagAsync", "POST", "/webinars/{webinarId}/branding/name_tags", "Create custom name tags for webinar speakers and panelists"),
        new("Webinars", "updateWebinarBrandingNameTag", "UpdateWebinarBrandingNameTagAsync", "PATCH", "/webinars/{webinarId}/branding/name_tags/{nameTagId}", "Update a panelist's custom name tag design and labels"),
        new("Webinars", "deleteWebinarBrandingVB", "DeleteWebinarBrandingVirtualBackgroundAsync", "DELETE", "/webinars/{webinarId}/branding/virtual_backgrounds", "Delete virtual background images configured for a webinar"),
        new("Webinars", "setWebinarBrandingVB", "SetWebinarBrandingVirtualBackgroundsAsync", "PATCH", "/webinars/{webinarId}/branding/virtual_backgrounds", "Set default virtual background image for webinar panelists"),
        new("Webinars", "uploadWebinarBrandingVB", "UploadWebinarBrandingVirtualBackgroundAsync", "POST", "/webinars/{webinarId}/branding/virtual_backgrounds", "Upload a custom virtual background image file for a webinar"),
        new("Webinars", "deleteWebinarBrandingWallpaper", "DeleteWebinarBrandingWallpaperAsync", "DELETE", "/webinars/{webinarId}/branding/wallpaper", "Delete custom wallpaper background image from a webinar"),
        new("Webinars", "uploadWebinarBrandingWallpaper", "UploadWebinarBrandingWallpaperAsync", "POST", "/webinars/{webinarId}/branding/wallpaper", "Upload a custom wallpaper background image file for a webinar"),
        new("Webinars", "webinarInviteLinksCreate", "CreateWebinarInviteLinksAsync", "POST", "/webinars/{webinarId}/invite_links", "Generate customized invite links for webinar attendees"),
        new("Webinars", "webinarLiveStreamingJoinToken", "GetWebinarLiveStreamingJoinTokenAsync", "GET", "/webinars/{webinarId}/jointoken/live_streaming", "Get join token for live streaming a webinar"),
        new("Webinars", "webinarLocalArchivingArchiveToken", "GetWebinarLocalArchivingTokenAsync", "GET", "/webinars/{webinarId}/jointoken/local_archiving", "Get token for local archiving of a webinar"),
        new("Webinars", "webinarLocalRecordingJoinToken", "GetWebinarLocalRecordingJoinTokenAsync", "GET", "/webinars/{webinarId}/jointoken/local_recording", "Get token for local recording of a webinar"),
        new("Webinars", "getWebinarLiveStreamDetails", "GetWebinarLiveStreamAsync", "GET", "/webinars/{webinarId}/livestream", "Get configured live stream settings, broadcast URL, and stream key"),
        new("Webinars", "webinarLiveStreamUpdate", "UpdateWebinarLiveStreamAsync", "PATCH", "/webinars/{webinarId}/livestream", "Configure live streaming broadcast URL, page URL, and stream key"),
        new("Webinars", "webinarLiveStreamStatusUpdate", "UpdateWebinarLiveStreamStatusAsync", "PATCH", "/webinars/{webinarId}/livestream/status", "Start or stop live streaming broadcast for a webinar"),
        new("Webinars", "webinarPanelistsDelete", "ClearWebinarPanelistsAsync", "DELETE", "/webinars/{webinarId}/panelists", "Remove all panelists from a webinar"),
        new("Webinars", "webinarPanelists", "ListWebinarPanelistsAsync", "GET", "/webinars/{webinarId}/panelists", "List all assigned panelists with join links for a webinar"),
        new("Webinars", "webinarPanelistCreate", "AddWebinarPanelistsAsync", "POST", "/webinars/{webinarId}/panelists", "Assign panelists and co-hosts to a webinar"),
        new("Webinars", "webinarPanelistDelete", "DeleteWebinarPanelistAsync", "DELETE", "/webinars/{webinarId}/panelists/{panelistId}", "Remove a specific panelist from a webinar"),
        new("Webinars", "webinarPolls", "ListWebinarPollsAsync", "GET", "/webinars/{webinarId}/polls", "List all polls and quizzes configured for a webinar"),
        new("Webinars", "webinarPollCreate", "CreateWebinarPollAsync", "POST", "/webinars/{webinarId}/polls", "Create a poll or quiz for a webinar"),
        new("Webinars", "webinarPollDelete", "DeleteWebinarPollAsync", "DELETE", "/webinars/{webinarId}/polls/{pollId}", "Delete a poll or quiz from a webinar"),
        new("Webinars", "webinarPollGet", "GetWebinarPollAsync", "GET", "/webinars/{webinarId}/polls/{pollId}", "Retrieve questions and options of a webinar poll"),
        new("Webinars", "webinarPollUpdate", "UpdateWebinarPollAsync", "PUT", "/webinars/{webinarId}/polls/{pollId}", "Update questions, options, and quiz scoring for a webinar poll"),
        new("Webinars", "webinarRegistrants", "ListWebinarRegistrantsAsync", "GET", "/webinars/{webinarId}/registrants", "List approved, pending, or denied registrants for a webinar"),
        new("Webinars", "webinarRegistrantCreate", "AddWebinarRegistrantAsync", "POST", "/webinars/{webinarId}/registrants", "Register an attendee for a webinar with custom responses"),
        new("Webinars", "webinarRegistrantsQuestionsGet", "GetWebinarRegistrationQuestionsAsync", "GET", "/webinars/{webinarId}/registrants/questions", "Get custom registration form questions for a webinar"),
        new("Webinars", "webinarRegistrantQuestionUpdate", "UpdateWebinarRegistrationQuestionsAsync", "PATCH", "/webinars/{webinarId}/registrants/questions", "Configure custom registration questions for a webinar"),
        new("Webinars", "webinarRegistrantStatus", "UpdateWebinarRegistrantStatusAsync", "PUT", "/webinars/{webinarId}/registrants/status", "Approve, deny, or cancel webinar registrant admission"),
        new("Webinars", "deleteWebinarRegistrant", "DeleteWebinarRegistrantAsync", "DELETE", "/webinars/{webinarId}/registrants/{registrantId}", "Delete a registered attendee from a webinar"),
        new("Webinars", "webinarRegistrantGet", "GetWebinarRegistrantAsync", "GET", "/webinars/{webinarId}/registrants/{registrantId}", "Get details and unique join URL for a webinar registrant"),
        new("Webinars", "getWebinarSipDialingWithPasscode", "GetWebinarSipDialingAsync", "POST", "/webinars/{webinarId}/sip_dialing", "Request Cloud Room Connector (CRC) SIP dialing for webinar with passcode"),
        new("Webinars", "webinarStatus", "UpdateWebinarStatusAsync", "PUT", "/webinars/{webinarId}/status", "End an active webinar session"),
        new("Webinars", "webinarSurveyDelete", "DeleteWebinarSurveyAsync", "DELETE", "/webinars/{webinarId}/survey", "Delete post-webinar attendee survey"),
        new("Webinars", "webinarSurveyGet", "GetWebinarSurveyAsync", "GET", "/webinars/{webinarId}/survey", "Retrieve post-webinar survey questions, settings, and 3rd party URL"),
        new("Webinars", "webinarSurveyUpdate", "UpdateWebinarSurveyAsync", "PATCH", "/webinars/{webinarId}/survey", "Create or update post-webinar survey questions and feedback options"),
        new("Webinars", "webinarToken", "GetWebinarTokenAsync", "GET", "/webinars/{webinarId}/token", "Generate user join or host token for webinar"),
        new("Webinars", "getTrackingSources", "GetWebinarTrackingSourcesAsync", "GET", "/webinars/{webinarId}/tracking_sources", "List campaign tracking sources and referral stats for webinar"),

        // 8. Templates (2 tools)
        new("Templates", "listMeetingTemplates", "ListMeetingTemplatesAsync", "GET", "/users/{userId}/meeting_templates", "List reusable meeting templates available for a user"),
        new("Templates", "meetingTemplateCreate", "CreateMeetingTemplateAsync", "POST", "/users/{userId}/meeting_templates", "Create a reusable meeting template from an existing meeting"),

        // 9. Live Meeting Controls (4 tools)
        new("Live Meeting Controls", "deleteMeetingChatMessageById", "DeleteLiveMeetingChatMessageAsync", "DELETE", "/live_meetings/{meetingId}/chat/messages/{messageId}", "Delete a chat message from an active live meeting session"),
        new("Live Meeting Controls", "updateMeetingChatMessageById", "UpdateLiveMeetingChatMessageAsync", "PATCH", "/live_meetings/{meetingId}/chat/messages/{messageId}", "Edit or censor a chat message in an active live meeting session"),
        new("Live Meeting Controls", "inMeetingControl", "InMeetingControlAsync", "PATCH", "/live_meetings/{meetingId}/events", "Send in-meeting moderation event (remove participant, callout room system, update waiting room, toggle AI companion)"),
        new("Live Meeting Controls", "meetingRTMSStatusUpdate", "UpdateMeetingRtmsStatusAsync", "PATCH", "/live_meetings/{meetingId}/rtms_app/status", "Update real-time media streaming (RTMS) app status for a participant"),

        // 10. Tracking Fields (5 tools)
        new("Tracking Fields", "trackingfieldList", "ListTrackingFieldsAsync", "GET", "/tracking_fields", "List custom tracking fields for account meetings and webinars"),
        new("Tracking Fields", "trackingfieldCreate", "CreateTrackingFieldAsync", "POST", "/tracking_fields", "Create a custom tracking field for cost center, department, or project attribution"),
        new("Tracking Fields", "trackingfieldDelete", "DeleteTrackingFieldAsync", "DELETE", "/tracking_fields/{fieldId}", "Permanently delete a custom tracking field"),
        new("Tracking Fields", "trackingfieldGet", "GetTrackingFieldAsync", "GET", "/tracking_fields/{fieldId}", "Get configuration and recommended values of a custom tracking field"),
        new("Tracking Fields", "trackingfieldUpdate", "UpdateTrackingFieldAsync", "PATCH", "/tracking_fields/{fieldId}", "Update tracking field label, required status, and value options"),

        // 11. SIP Phones (4 tools)
        new("SIP Phones", "ListSIPPhonePhones", "ListSipPhonesAsync", "GET", "/sip_phones/phones", "List provisioned SIP phone devices across the account"),
        new("SIP Phones", "EnableSIPPhonePhones", "EnableSipPhoneAsync", "POST", "/sip_phones/phones", "Provision and enable a SIP phone device for a user"),
        new("SIP Phones", "deleteSIPPhonePhones", "DeleteSipPhoneAsync", "DELETE", "/sip_phones/phones/{phoneId}", "Delete and de-provision a SIP phone device"),
        new("SIP Phones", "UpdateSIPPhonePhones", "UpdateSipPhoneAsync", "PATCH", "/sip_phones/phones/{phoneId}", "Update SIP phone configuration, user assignment, and transport protocol"),

        // 12. TSP (8 tools)
        new("TSP", "tsp", "GetAccountTspAsync", "GET", "/tsp", "Get account-level Telephony Service Provider (TSP) information"),
        new("TSP", "tspUpdate", "UpdateAccountTspAsync", "PATCH", "/tsp", "Update account-level Telephony Service Provider (TSP) configuration"),
        new("TSP", "userTSPs", "ListUserTspsAsync", "GET", "/users/{userId}/tsp", "List Telephony Service Provider accounts configured for a specific user"),
        new("TSP", "userTSPCreate", "CreateUserTspAsync", "POST", "/users/{userId}/tsp", "Add a Telephony Service Provider account for a user"),
        new("TSP", "tspUrlUpdate", "UpdateUserTspUrlAsync", "PATCH", "/users/{userId}/tsp/settings", "Configure global dial-in URL for a user's TSP audio conferencing"),
        new("TSP", "userTSPDelete", "DeleteUserTspAsync", "DELETE", "/users/{userId}/tsp/{tspId}", "Delete a user's Telephony Service Provider account"),
        new("TSP", "userTSP", "GetUserTspAsync", "GET", "/users/{userId}/tsp/{tspId}", "Get credentials and dial-in details of a user's TSP account"),
        new("TSP", "userTSPUpdate", "UpdateUserTspAsync", "PATCH", "/users/{userId}/tsp/{tspId}", "Update credentials and dial-in numbers for a user's TSP account"),

        // 13. Devices & H.323 (17 tools)
        new("Devices & H.323", "listDevices", "ListDevicesAsync", "GET", "/devices", "List Zoom Rooms and Zoom Device Management (ZDM) enrolled devices"),
        new("Devices & H.323", "addDevice", "CreateDeviceAsync", "POST", "/devices", "Add a hardware device to Zoom Device Management (ZDM)"),
        new("Devices & H.323", "Getzdmgroupinfo", "ListDeviceGroupsAsync", "GET", "/devices/groups", "Get Zoom Device Management (ZDM) group profiles and tags"),
        new("Devices & H.323", "Assigndevicetoauser/commonarea", "AssignZpaDeviceAsync", "POST", "/devices/zpa/assignment", "Assign a Zoom Phone Appliance (ZPA) to a user or common area"),
        new("Devices & H.323", "GetZpaDeviceListProfileSettingOfaUser", "GetZpaUserSettingsAsync", "GET", "/devices/zpa/settings", "Get ZPA device profile settings and line key configuration for a user"),
        new("Devices & H.323", "UpgradeZpas/app", "UpgradeZpaAsync", "POST", "/devices/zpa/upgrade", "Trigger firmware or application upgrade on Zoom Phone Appliances"),
        new("Devices & H.323", "DeleteZpaDeviceByVendorAndMacAddress", "DeleteZpaDeviceAsync", "DELETE", "/devices/zpa/vendors/{vendor}/mac_addresses/{macAddress}", "Delete ZPA device by vendor name and MAC address"),
        new("Devices & H.323", "GetZpaVersioninfo", "GetZpaVersionsAsync", "GET", "/devices/zpa/zdm_groups/{zdmGroupId}/versions", "Get available ZPA firmware versions for a ZDM device group"),
        new("Devices & H.323", "deleteDevice", "DeleteDeviceAsync", "DELETE", "/devices/{deviceId}", "Delete a hardware device from Zoom Device Management"),
        new("Devices & H.323", "getDevice", "GetDeviceAsync", "GET", "/devices/{deviceId}", "Retrieve device hardware, OS, and status from Zoom Device Management"),
        new("Devices & H.323", "updateDevice", "UpdateDeviceAsync", "PATCH", "/devices/{deviceId}", "Update device name, tags, or settings in Zoom Device Management"),
        new("Devices & H.323", "assginGroup", "AssignDeviceGroupAsync", "PATCH", "/devices/{deviceId}/assign_group", "Assign a device to a Zoom Device Management group"),
        new("Devices & H.323", "changeDeviceAssociation", "ChangeDeviceAssociationAsync", "PATCH", "/devices/{deviceId}/assignment", "Change device association to a different user, room, or common area"),
        new("Devices & H.323", "deviceList", "ListH323DevicesAsync", "GET", "/h323/devices", "List provisioned H.323/SIP conference room systems"),
        new("Devices & H.323", "deviceCreate", "CreateH323DeviceAsync", "POST", "/h323/devices", "Register a new H.323/SIP room system with IP and encryption settings"),
        new("Devices & H.323", "deviceDelete", "DeleteH323DeviceAsync", "DELETE", "/h323/devices/{deviceId}", "Delete a registered H.323/SIP conference room system"),
        new("Devices & H.323", "deviceUpdate", "UpdateH323DeviceAsync", "PATCH", "/h323/devices/{deviceId}", "Update IP address, name, or encryption protocol for an H.323/SIP device"),
    };
}
